class Constants():
    INFECTION_RADIOUS = [0.2, 0.5]
    RECOVERY_TIME = [7,30]
    INCUBATION_PERIOD = [2,10]
    INFECTION_PROBABILITY_PER_TIME_PERIOD = [0.3, 0.5]
    NUMBER_OF_SUBJECTS = 10
    SOCIAL_DISTANCE_FACTOR = 0